### PR TITLE
INTMDB 650 CloudProvider Access profile changes

### PR DESCRIPTION
**Pull request by govardhanpagidi**
## Description

CloudProvider Access profile changes
Link to any related issue(s): 

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code
- [x] For CFN Resources: I have released by changes in the private registry and proved by change works in Atlas

### CODE REVIEW

**Comment by govardhanpagidi** [comment]
Tested with Private Extension 

image

**Comment by maastha** [comment]
What is the plan for this? Since this is unstable right?

**Comment by Zuhairahmed** [comment]
> @govardhanpagidi What is the plan for this? Since this is unstable right?

Just to have template to pick up for future developers once CFN allows support for these types of resources. Currently it is a CFN limitation to not allow 3rd party resources to assign IAM roles from CFN Public Registry.

**Comment by govardhanpagidi** [comment]
@Zuhairahmed and @maastha  this resource just works for private extension, but for global publishing we have to wait until AWS provides any approach to solve the IAM Role Assignment issue.

**Review by maastha — APPROVED** [review]
LGTM

**Pull request merged**
