### PR TITLE
feat: INTMDB 1005 Serverless private endpoint

### PR DESCRIPTION
**Pull request by Adelmar92**
## Proposed changes

Added new resource Pirvate Endpoint Serverless:

- this version of private endpoint serverless, has 2 flows:
- Without AWS private endpoint
- With AWS private endpoint

### Without AWS Private Endpoint Flow:
In this configuration, you have the flexibility to establish an Atlas private endpoint independently. By opting not to immediately connect it, you can manually set up the linkage with an AWS private endpoint or Azure. Simply set the CreateAndAssignAWSPrivateEndpoint attribute to false during resource creation.

### With AWS Private Endpoint Flow:
For a streamlined experience, you can enable the automatic generation of both Atlas private and AWS private endpoints, along with their interconnection, all within a single resource. Achieve this by configuring the CreateAndAssignAWSPrivateEndpoint attribute as true and supplying the following configuration structure:

``` json
"AwsPrivateEndpointConfigurationProperties": {
    "VpcId": "vpc-xxxxxx",
    "SubnetIds": ["subnet-xxxxx", "subnet-yyyyy"],
    "Region": "us_east_1"
}
```

cfn testing:
image

stack testing:
### Without aws Private endpoint
image

image

### With aws Private endpoint
image

result:
atlas private endpoint 
image

aws private endpoint 
image

_Jira ticket:_ [INTMDB-1005](https://jira.mongodb.org/browse/INTMDB-1005)

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)
- [ ] This change requires a documentation update

## Manual QA performed:

- [ ] cfn invoke for each of CRUDL/cfn test
- [ ] Updated resource in  [example](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/examples)
- [ ] Published to AWS private registry
- [ ] Used the template in [example](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/examples) to create and update a stack in AWS
- [ ] Deleted stack to ensure resources are deleted
- [ ] Created multiple resources in same stack
- [ ] Validated in Atlas UI
- [ ] Included screenshots

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run `make fmt` and formatted my code
- [ ] For CFN Resources: I have released by changes in the private registry and proved by change
  works in Atlas

### CODE REVIEW

**Comment by govardhanpagidi** [comment]
@Adelmar92  we need to add contract testing as well.

**Comment by maastha** [comment]
@Adelmar92  Could you please include a manual QA/testing guide as well when adding any new features?
See following for examples:
https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/cfn-resources/ldap-configuration/test/README.md
https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/cfn-resources/cloud-backup-snapshot/test/README.md 

The idea is that testing/any manual setup required for testing should be clearly outlined, this would help us in later automating all testing. 
This also helps to outline the expected result from the resource on successful implementation.

**Comment by Adelmar92** [comment]
> @Adelmar92 Could you please include a manual QA/testing guide as well when adding any new features? See following for examples: https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/cfn-resources/ldap-configuration/test/README.md https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/cfn-resources/cloud-backup-snapshot/test/README.md
> 
> The idea is that testing/any manual setup required for testing should be clearly outlined, this would help us in later automating all testing. This also helps to outline the expected result from the resource on successful implementation.

Done!

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Review by govardhanpagidi — APPROVED** [review]

**Pull request merged**
