### PR TITLE
INTMDB-396: Autoclose stale issues and PRs updates to README.md

### PR DESCRIPTION
**Pull request by Zuhairahmed**
## Description

Updates to README.md - Autoclose stale issues and PRs

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run `make fmt` and formatted my code

### CODE REVIEW

**Comment by Zuhairahmed** [comment]
@themantissa requesting review

**Review by themantissa — APPROVED** [review]
Let's wait to actually action on this till we get things more fixed up. We'll want to make sure we fix anything currently in the issues that are a bug.  So start this policy basically from this day forward.

**Comment by Zuhairahmed** [comment]
makes sense, will do

**Comment by Zuhairahmed** [comment]
@andreaangiolillo can you review this PR / add similar bot you did for Terraform repo (same rules are fine)? now that we are further along good to have our users practice good hygiene in keeping our Issues + PR backlog not stale

**Comment by andreaangiolillo** [comment]
@Zuhairahmed PR is ready here https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/312. I am also updating the README.MD file there so you can close this PR if you want. Thanks

**Comment by Zuhairahmed** [comment]
Closing given new PR created by @andreaangiolillo in #312

**Pull request closed without merging**
