### PR TITLE
feat: Update resource-role.yaml with KMS Permissions

### PR DESCRIPTION
**Pull request by matthew-ewing**
## Proposed changes
My organization has a use case where we would like to use an existing KMS Customer Managed Key in our AWS accounts to encrypt the AWS SecretsManager resources accessed by this stack. In order to do so, the resource role needs access to KMS.

_Jira ticket:_ CLOUDP-#

Currently we receive an error when attempting to create an MongoDB Atlas Cluster using this specific configuration: `AtlasCluster Resource handler returned message: "AccessDeinedException: Access to KMS is not allowed`

Link to any related issue(s): 
Related to internal support case 01334748

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)
- [ ] This change requires a documentation update
- [ ] If changes include removal or addition of 3rd party GitHub actions, I updated our internal document. Reach out to the APIx Integration slack channel to get access to the internal document.

## Manual QA performed:

- [ ] cfn invoke for each of CRUDL/cfn test
- [ ] Updated resource in  [example](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/examples)
- [ ] Published to AWS private registry
- [ ] Used the template in [example](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/examples) to create and update a stack in AWS
- [ ] Deleted stack to ensure resources are deleted
- [ ] Created multiple resources in same stack
- [ ] Validated in Atlas UI
- [ ] Included screenshots

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that this change does not generate any credentials and that **they are NOT accidentally logged anywhere**.
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run `make fmt` and formatted my code
- [ ] For CFN Resources: I have released by changes in the private registry and proved by change
  works in Atlas

### CODE REVIEW

**Comment by lantoli** [comment]
Thanks @matthew-ewing for creating this PR.  Unfortunately I don't think it will have the effect you need. The permissions in this file are only for the execution of the CRUDL operations, of `MongoDB::Atlas::Cluster` in this case, i.e. when the cluster is created, read, updated, listed, deleted. In those operations KMS is not used.

You will probably want to change permissions for KMS policy or for the IAM role that executes your CFN stack:
cfn_stack

I hope this helps. If you have any other question please let me know.

**Comment by matthew-ewing** [comment]
I believe the issue I am running into is when this role attempts to create the cluster, it reads from secrets manager to obtain credentials. The secrets stored in secrets manager are encrypted using an AWS KMS customer managed key. I think that is why I am seeing this specific error on cluster create. Although it would appear KMS is not being used, permissions for KMS are required in order to perform `secretsmanager:GetSecretValue` for secrets encrypted with a CMK.

**Comment by AgustinBettati** [comment]
Hi @matthew-ewing.
Wanted to confirm if you where able to reference the note we have in our [README.md](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master?tab=readme-ov-file#2-configure-your-profile) file related to using AWS KMS key to handle encryption of your secret. This mentions specific resource policies that need to be configured in the KMS key so that Secrets Manager has the appropriate access.

**Comment by lantoli** [comment]
hi @matthew-ewing , as @AgustinBettati mentions you should be able to change the key policy to allow access to Secrets Manager.  

There is also more info in [Key Policies](https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html)

**Comment by lantoli** [comment]
hi @matthew-ewing, I'm not sure that file is really used by the resource operations.  Can you try to use an Execute Role when activating the `MongoDB::atlas::Cluster` resource with the KMS permissions you want to try?

role

**Pull request closed without merging**
