### PR TITLE
feat: upgrading go version to 1.21

### PR DESCRIPTION
**Pull request by govardhanpagidi**
feat: upgrading go version to 1.21

_Jira ticket:_ CLOUDP-# https://jira.mongodb.org/browse/INTMDB-1210

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)
- [ ] This change requires a documentation update

## Manual QA performed:

- [ ] cfn invoke for each of CRUDL/cfn test
- [ ] Updated resource in  [example](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/examples)
- [ ] Published to AWS private registry
- [ ] Used the template in [example](https://github.com/mongodb/mongodbatlas-cloudformation-resources/tree/master/examples) to create and update a stack in AWS
- [ ] Deleted stack to ensure resources are deleted
- [ ] Created multiple resources in same stack
- [ ] Validated in Atlas UI
- [ ] Included screenshots

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code
- [ ] For CFN Resources: I have released by changes in the private registry and proved by change
  works in Atlas

### CODE REVIEW

**Review by marcosuma — APPROVED** [review]

**Review by lantoli — CHANGES_REQUESTED** [review]
Please read notes and description in: https://jira.mongodb.org/browse/INTMDB-1210

Publishing is not updated:
image: 'aws/codebuild/amazonlinux2-x86_64-standard:5.0'  , golang: 1.20. The Docker image in Codebuild uses 1.20.

In go 1.21 the best way to change go.mod is to do it like: https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/go.mod#L3C1-L5
 
.tool-versions is not updated to 1.21.3

Doc is not changed, e.g. v1.20 in CONTRIBUTING.md

**Comment by govardhanpagidi** [comment]
@lantoli I've addressed the comments

**Review by Adelmar92 — DISMISSED** [review]

**Comment by lantoli** [comment]
> @lantoli I've addressed the comments

@govardhanpagidi Thanks I think the publishing Docker image is still missing: image: 'aws/codebuild/amazonlinux2-x86_64-standard:5.0' , golang: 1.20. The Docker image in Codebuild uses 1.20.

**Review by lantoli — CHANGES_REQUESTED** [review]
The publishing Docker image is still missing: image: 'aws/codebuild/amazonlinux2-x86_64-standard:5.0' , golang: 1.20. The Docker image in Codebuild uses 1.20.

**Comment by govardhanpagidi** [comment]
thanks @lantoli, updated the same

**Review by lantoli — CHANGES_REQUESTED** [review]
@govardhanpagidi have you tried to create a SSM doc and publish a resource? I'm not sure that docker image have Go 1.21

**Comment by govardhanpagidi** [comment]
@lantoli I've created the document (verison 56) in AWS SSM

**Comment by lantoli** [comment]
> @lantoli I've created the document (verison 56) in AWS SSM

@govardhanpagidi I would prefer that you don't change the main AWS SSM doc until the PR is approved and merged. 

It's better to clone the doc and point to the cloned doc from your PR to do the changes and testing, so you don't affect the real SSM doc in the meantime.

That said, have you tried to do a publishing with Go 1.21? is positive, can you please share the link to the SSM and Codebuilld execution?

Thanks

 cc @AgustinBettati

**Comment by govardhanpagidi** [comment]
@lantoli the document is not set to default, for the next publish we can set as to the latest(version 56)

the [github workflow](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/.github/workflows/cfn-publish-resource.yaml) will internally triggers the [SSM Automation document](https://us-east-1.console.aws.amazon.com/systems-manager/documents/CFN-MongoDB-Atlas-Resource-Register/description?region=us-east-1)

**Comment by lantoli** [comment]
@govardhanpagidi  If that's fine I'm going to close this PR and we'll wait until resources are published as v2, then I'll continue with this work and investigate what Docker image to use in publishing.

thanks!

**Pull request closed without merging**
