### PR TITLE
Maintenence Window : Replaced keys with profile

### PR DESCRIPTION
**Pull request by SuperMohit**
## Description

Replaced Keys with Profile for maintenance window.

Screenshot 2023-02-22 at 11 38 25 AM

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Comment by SuperMohit** [comment]
**Note:**
P1: readOnlyProperties:  Resource properties that can be returned by a read or list request, but can't be set by the user.
In this resource, GroupId is set as Primary Identifier. So, it has to be either in the readOnly or createOnly list. This has been set as readOnly property, so violates P1. So, when executing the test we have a warning for the same.

**Comment by SuperMohit** [comment]
Works if I output read-only props. If you try to output any other field that is not read-only it fails.
Screenshot 2023-02-22 at 12 26 43 PM

**Comment by andreaangiolillo** [comment]
@SuperMohit Yes, I got the same behaviour. 

According to the [AWS Doc](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-schema.html) seems that you cannot return `writeOnlyProperties` in the read but only readOnly and primary identifiers

> readOnlyProperties
> Resource properties that can be returned by a read or list request, but can't be set by the user.

> writeOnlyProperties
> Resource properties that can be specified by the user, but can't be returned by a read or list request. Write-only properties are often used to contain passwords, secrets, or other sensitive data.

**Review by colm-quinn — DISMISSED** [review]
LGTM, thanks for the updates

**Comment by colm-quinn** [comment]
> @govardhanpagidi @andreaangiolillo @Adelmar92 @maastha did you guys see the same behavior with non - readonly props? Works if I output read-only props. If you try to output any other field that is not read-only it fails. Screenshot 2023-02-22 at 12 26 43 PM

Just before merging, I'm a little unclear if this conversation is resolved & the P1 concern has been removed. Can you clarify what has been decided here?

**Comment by SuperMohit** [comment]
> > @govardhanpagidi @andreaangiolillo @Adelmar92 @maastha did you guys see the same behavior with non - readonly props? Works if I output read-only props. If you try to output any other field that is not read-only it fails. Screenshot 2023-02-22 at 12 26 43 PM
> 
> Just before merging, I'm a little unclear if this conversation is resolved & the P1 concern has been removed. Can you clarify what has been decided here?

The behavior is the same, only read-only props are available in the Output. Anything else won't be available.

**Comment by govardhanpagidi** [comment]
@colm-quinn Can you approve this PR?

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Review by colm-quinn — APPROVED** [review]

**Pull request merged**
